replicaCount: 2
image:
  repository: docker.io/0marmohamed/flask-kubernetes
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
