replicaCount: 2
image:
  repository: githubactionsiti2025.azurecr.io/flask-kubernetes
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 5000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi