replicaCount: 2
image:
  repository: githubactionsiti2025.azurecr.io/flask-app
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: LoadBalancer
  port: 5000
