name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: githubactionsiti2025.azurecr.io
  IMAGE_NAME: ${{ github.repository }}
  RELEASE_NAME: flask-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.8.0'

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install ${{ env.RELEASE_NAME }} ./flask-app-chart \
          --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
          --set image.tag=latest