name: Deploy with Helm

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to ACR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login githubactionsiti2025.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t githubactionsiti2025.azurecr.io/flask-app:latest .
          docker push githubactionsiti2025.azurecr.io/flask-app:latest

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Deploy to AKS
        run: |
          helm upgrade --install flask-app-release ./helm/flask-app \
            --set image.repository=githubactionsiti2025.azurecr.io/flask-app \
            --set image.tag=latest
