name: Deploy Flask App to Kubernetes via Helm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: omar-mohamed-abdelsalam-flask-kubernetes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ vars.CONTAINER_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ vars.CONTAINER_REGISTRY }}/$IMAGE_NAME:latest .
          docker push ${{ vars.CONTAINER_REGISTRY }}/$IMAGE_NAME:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy using Helm
        run: |
          helm upgrade --install flask-app ./flask-k8s-helm \
            --set image.repository=${{ vars.CONTAINER_REGISTRY }}/$IMAGE_NAME \
            --set image.tag=latest \
            --set replicaCount=2